# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/SirPanda/Desktop/99.Thesis/02.libcsp/libcsp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/SirPanda/Desktop/99.Thesis/02.libcsp/libcsp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/SirPanda/Desktop/99.Thesis/02.libcsp/libcsp/CMakeFiles /home/SirPanda/Desktop/99.Thesis/02.libcsp/libcsp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/SirPanda/Desktop/99.Thesis/02.libcsp/libcsp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libcsp

# Build rule for target.
libcsp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libcsp
.PHONY : libcsp

# fast build rule for target.
libcsp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/build
.PHONY : libcsp/fast

#=============================================================================
# Target rules for targets named if_zmq

# Build rule for target.
if_zmq: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 if_zmq
.PHONY : if_zmq

# fast build rule for target.
if_zmq/fast:
	$(MAKE) $(MAKESILENT) -f src/interfaces/CMakeFiles/if_zmq.dir/build.make src/interfaces/CMakeFiles/if_zmq.dir/build
.PHONY : if_zmq/fast

#=============================================================================
# Target rules for targets named csp_server_client

# Build rule for target.
csp_server_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 csp_server_client
.PHONY : csp_server_client

# fast build rule for target.
csp_server_client/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/csp_server_client.dir/build.make examples/CMakeFiles/csp_server_client.dir/build
.PHONY : csp_server_client/fast

#=============================================================================
# Target rules for targets named csp_arch

# Build rule for target.
csp_arch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 csp_arch
.PHONY : csp_arch

# fast build rule for target.
csp_arch/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/csp_arch.dir/build.make examples/CMakeFiles/csp_arch.dir/build
.PHONY : csp_arch/fast

#=============================================================================
# Target rules for targets named zmqproxy

# Build rule for target.
zmqproxy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zmqproxy
.PHONY : zmqproxy

# fast build rule for target.
zmqproxy/fast:
	$(MAKE) $(MAKESILENT) -f examples/CMakeFiles/zmqproxy.dir/build.make examples/CMakeFiles/zmqproxy.dir/build
.PHONY : zmqproxy/fast

src/arch/posix/csp_clock.o: src/arch/posix/csp_clock.c.o
.PHONY : src/arch/posix/csp_clock.o

# target to build an object file
src/arch/posix/csp_clock.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/arch/posix/csp_clock.c.o
.PHONY : src/arch/posix/csp_clock.c.o

src/arch/posix/csp_clock.i: src/arch/posix/csp_clock.c.i
.PHONY : src/arch/posix/csp_clock.i

# target to preprocess a source file
src/arch/posix/csp_clock.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/arch/posix/csp_clock.c.i
.PHONY : src/arch/posix/csp_clock.c.i

src/arch/posix/csp_clock.s: src/arch/posix/csp_clock.c.s
.PHONY : src/arch/posix/csp_clock.s

# target to generate assembly for a file
src/arch/posix/csp_clock.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/arch/posix/csp_clock.c.s
.PHONY : src/arch/posix/csp_clock.c.s

src/arch/posix/csp_queue.o: src/arch/posix/csp_queue.c.o
.PHONY : src/arch/posix/csp_queue.o

# target to build an object file
src/arch/posix/csp_queue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/arch/posix/csp_queue.c.o
.PHONY : src/arch/posix/csp_queue.c.o

src/arch/posix/csp_queue.i: src/arch/posix/csp_queue.c.i
.PHONY : src/arch/posix/csp_queue.i

# target to preprocess a source file
src/arch/posix/csp_queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/arch/posix/csp_queue.c.i
.PHONY : src/arch/posix/csp_queue.c.i

src/arch/posix/csp_queue.s: src/arch/posix/csp_queue.c.s
.PHONY : src/arch/posix/csp_queue.s

# target to generate assembly for a file
src/arch/posix/csp_queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/arch/posix/csp_queue.c.s
.PHONY : src/arch/posix/csp_queue.c.s

src/arch/posix/csp_semaphore.o: src/arch/posix/csp_semaphore.c.o
.PHONY : src/arch/posix/csp_semaphore.o

# target to build an object file
src/arch/posix/csp_semaphore.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/arch/posix/csp_semaphore.c.o
.PHONY : src/arch/posix/csp_semaphore.c.o

src/arch/posix/csp_semaphore.i: src/arch/posix/csp_semaphore.c.i
.PHONY : src/arch/posix/csp_semaphore.i

# target to preprocess a source file
src/arch/posix/csp_semaphore.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/arch/posix/csp_semaphore.c.i
.PHONY : src/arch/posix/csp_semaphore.c.i

src/arch/posix/csp_semaphore.s: src/arch/posix/csp_semaphore.c.s
.PHONY : src/arch/posix/csp_semaphore.s

# target to generate assembly for a file
src/arch/posix/csp_semaphore.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/arch/posix/csp_semaphore.c.s
.PHONY : src/arch/posix/csp_semaphore.c.s

src/arch/posix/csp_system.o: src/arch/posix/csp_system.c.o
.PHONY : src/arch/posix/csp_system.o

# target to build an object file
src/arch/posix/csp_system.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/arch/posix/csp_system.c.o
.PHONY : src/arch/posix/csp_system.c.o

src/arch/posix/csp_system.i: src/arch/posix/csp_system.c.i
.PHONY : src/arch/posix/csp_system.i

# target to preprocess a source file
src/arch/posix/csp_system.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/arch/posix/csp_system.c.i
.PHONY : src/arch/posix/csp_system.c.i

src/arch/posix/csp_system.s: src/arch/posix/csp_system.c.s
.PHONY : src/arch/posix/csp_system.s

# target to generate assembly for a file
src/arch/posix/csp_system.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/arch/posix/csp_system.c.s
.PHONY : src/arch/posix/csp_system.c.s

src/arch/posix/csp_time.o: src/arch/posix/csp_time.c.o
.PHONY : src/arch/posix/csp_time.o

# target to build an object file
src/arch/posix/csp_time.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/arch/posix/csp_time.c.o
.PHONY : src/arch/posix/csp_time.c.o

src/arch/posix/csp_time.i: src/arch/posix/csp_time.c.i
.PHONY : src/arch/posix/csp_time.i

# target to preprocess a source file
src/arch/posix/csp_time.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/arch/posix/csp_time.c.i
.PHONY : src/arch/posix/csp_time.c.i

src/arch/posix/csp_time.s: src/arch/posix/csp_time.c.s
.PHONY : src/arch/posix/csp_time.s

# target to generate assembly for a file
src/arch/posix/csp_time.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/arch/posix/csp_time.c.s
.PHONY : src/arch/posix/csp_time.c.s

src/arch/posix/pthread_queue.o: src/arch/posix/pthread_queue.c.o
.PHONY : src/arch/posix/pthread_queue.o

# target to build an object file
src/arch/posix/pthread_queue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/arch/posix/pthread_queue.c.o
.PHONY : src/arch/posix/pthread_queue.c.o

src/arch/posix/pthread_queue.i: src/arch/posix/pthread_queue.c.i
.PHONY : src/arch/posix/pthread_queue.i

# target to preprocess a source file
src/arch/posix/pthread_queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/arch/posix/pthread_queue.c.i
.PHONY : src/arch/posix/pthread_queue.c.i

src/arch/posix/pthread_queue.s: src/arch/posix/pthread_queue.c.s
.PHONY : src/arch/posix/pthread_queue.s

# target to generate assembly for a file
src/arch/posix/pthread_queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/arch/posix/pthread_queue.c.s
.PHONY : src/arch/posix/pthread_queue.c.s

src/crypto/csp_hmac.o: src/crypto/csp_hmac.c.o
.PHONY : src/crypto/csp_hmac.o

# target to build an object file
src/crypto/csp_hmac.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/crypto/csp_hmac.c.o
.PHONY : src/crypto/csp_hmac.c.o

src/crypto/csp_hmac.i: src/crypto/csp_hmac.c.i
.PHONY : src/crypto/csp_hmac.i

# target to preprocess a source file
src/crypto/csp_hmac.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/crypto/csp_hmac.c.i
.PHONY : src/crypto/csp_hmac.c.i

src/crypto/csp_hmac.s: src/crypto/csp_hmac.c.s
.PHONY : src/crypto/csp_hmac.s

# target to generate assembly for a file
src/crypto/csp_hmac.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/crypto/csp_hmac.c.s
.PHONY : src/crypto/csp_hmac.c.s

src/crypto/csp_sha1.o: src/crypto/csp_sha1.c.o
.PHONY : src/crypto/csp_sha1.o

# target to build an object file
src/crypto/csp_sha1.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/crypto/csp_sha1.c.o
.PHONY : src/crypto/csp_sha1.c.o

src/crypto/csp_sha1.i: src/crypto/csp_sha1.c.i
.PHONY : src/crypto/csp_sha1.i

# target to preprocess a source file
src/crypto/csp_sha1.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/crypto/csp_sha1.c.i
.PHONY : src/crypto/csp_sha1.c.i

src/crypto/csp_sha1.s: src/crypto/csp_sha1.c.s
.PHONY : src/crypto/csp_sha1.s

# target to generate assembly for a file
src/crypto/csp_sha1.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/crypto/csp_sha1.c.s
.PHONY : src/crypto/csp_sha1.c.s

src/csp_bridge.o: src/csp_bridge.c.o
.PHONY : src/csp_bridge.o

# target to build an object file
src/csp_bridge.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_bridge.c.o
.PHONY : src/csp_bridge.c.o

src/csp_bridge.i: src/csp_bridge.c.i
.PHONY : src/csp_bridge.i

# target to preprocess a source file
src/csp_bridge.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_bridge.c.i
.PHONY : src/csp_bridge.c.i

src/csp_bridge.s: src/csp_bridge.c.s
.PHONY : src/csp_bridge.s

# target to generate assembly for a file
src/csp_bridge.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_bridge.c.s
.PHONY : src/csp_bridge.c.s

src/csp_buffer.o: src/csp_buffer.c.o
.PHONY : src/csp_buffer.o

# target to build an object file
src/csp_buffer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_buffer.c.o
.PHONY : src/csp_buffer.c.o

src/csp_buffer.i: src/csp_buffer.c.i
.PHONY : src/csp_buffer.i

# target to preprocess a source file
src/csp_buffer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_buffer.c.i
.PHONY : src/csp_buffer.c.i

src/csp_buffer.s: src/csp_buffer.c.s
.PHONY : src/csp_buffer.s

# target to generate assembly for a file
src/csp_buffer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_buffer.c.s
.PHONY : src/csp_buffer.c.s

src/csp_conn.o: src/csp_conn.c.o
.PHONY : src/csp_conn.o

# target to build an object file
src/csp_conn.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_conn.c.o
.PHONY : src/csp_conn.c.o

src/csp_conn.i: src/csp_conn.c.i
.PHONY : src/csp_conn.i

# target to preprocess a source file
src/csp_conn.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_conn.c.i
.PHONY : src/csp_conn.c.i

src/csp_conn.s: src/csp_conn.c.s
.PHONY : src/csp_conn.s

# target to generate assembly for a file
src/csp_conn.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_conn.c.s
.PHONY : src/csp_conn.c.s

src/csp_crc32.o: src/csp_crc32.c.o
.PHONY : src/csp_crc32.o

# target to build an object file
src/csp_crc32.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_crc32.c.o
.PHONY : src/csp_crc32.c.o

src/csp_crc32.i: src/csp_crc32.c.i
.PHONY : src/csp_crc32.i

# target to preprocess a source file
src/csp_crc32.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_crc32.c.i
.PHONY : src/csp_crc32.c.i

src/csp_crc32.s: src/csp_crc32.c.s
.PHONY : src/csp_crc32.s

# target to generate assembly for a file
src/csp_crc32.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_crc32.c.s
.PHONY : src/csp_crc32.c.s

src/csp_debug.o: src/csp_debug.c.o
.PHONY : src/csp_debug.o

# target to build an object file
src/csp_debug.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_debug.c.o
.PHONY : src/csp_debug.c.o

src/csp_debug.i: src/csp_debug.c.i
.PHONY : src/csp_debug.i

# target to preprocess a source file
src/csp_debug.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_debug.c.i
.PHONY : src/csp_debug.c.i

src/csp_debug.s: src/csp_debug.c.s
.PHONY : src/csp_debug.s

# target to generate assembly for a file
src/csp_debug.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_debug.c.s
.PHONY : src/csp_debug.c.s

src/csp_dedup.o: src/csp_dedup.c.o
.PHONY : src/csp_dedup.o

# target to build an object file
src/csp_dedup.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_dedup.c.o
.PHONY : src/csp_dedup.c.o

src/csp_dedup.i: src/csp_dedup.c.i
.PHONY : src/csp_dedup.i

# target to preprocess a source file
src/csp_dedup.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_dedup.c.i
.PHONY : src/csp_dedup.c.i

src/csp_dedup.s: src/csp_dedup.c.s
.PHONY : src/csp_dedup.s

# target to generate assembly for a file
src/csp_dedup.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_dedup.c.s
.PHONY : src/csp_dedup.c.s

src/csp_hex_dump.o: src/csp_hex_dump.c.o
.PHONY : src/csp_hex_dump.o

# target to build an object file
src/csp_hex_dump.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_hex_dump.c.o
.PHONY : src/csp_hex_dump.c.o

src/csp_hex_dump.i: src/csp_hex_dump.c.i
.PHONY : src/csp_hex_dump.i

# target to preprocess a source file
src/csp_hex_dump.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_hex_dump.c.i
.PHONY : src/csp_hex_dump.c.i

src/csp_hex_dump.s: src/csp_hex_dump.c.s
.PHONY : src/csp_hex_dump.s

# target to generate assembly for a file
src/csp_hex_dump.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_hex_dump.c.s
.PHONY : src/csp_hex_dump.c.s

src/csp_id.o: src/csp_id.c.o
.PHONY : src/csp_id.o

# target to build an object file
src/csp_id.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_id.c.o
.PHONY : src/csp_id.c.o

src/csp_id.i: src/csp_id.c.i
.PHONY : src/csp_id.i

# target to preprocess a source file
src/csp_id.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_id.c.i
.PHONY : src/csp_id.c.i

src/csp_id.s: src/csp_id.c.s
.PHONY : src/csp_id.s

# target to generate assembly for a file
src/csp_id.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_id.c.s
.PHONY : src/csp_id.c.s

src/csp_iflist.o: src/csp_iflist.c.o
.PHONY : src/csp_iflist.o

# target to build an object file
src/csp_iflist.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_iflist.c.o
.PHONY : src/csp_iflist.c.o

src/csp_iflist.i: src/csp_iflist.c.i
.PHONY : src/csp_iflist.i

# target to preprocess a source file
src/csp_iflist.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_iflist.c.i
.PHONY : src/csp_iflist.c.i

src/csp_iflist.s: src/csp_iflist.c.s
.PHONY : src/csp_iflist.s

# target to generate assembly for a file
src/csp_iflist.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_iflist.c.s
.PHONY : src/csp_iflist.c.s

src/csp_init.o: src/csp_init.c.o
.PHONY : src/csp_init.o

# target to build an object file
src/csp_init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_init.c.o
.PHONY : src/csp_init.c.o

src/csp_init.i: src/csp_init.c.i
.PHONY : src/csp_init.i

# target to preprocess a source file
src/csp_init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_init.c.i
.PHONY : src/csp_init.c.i

src/csp_init.s: src/csp_init.c.s
.PHONY : src/csp_init.s

# target to generate assembly for a file
src/csp_init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_init.c.s
.PHONY : src/csp_init.c.s

src/csp_io.o: src/csp_io.c.o
.PHONY : src/csp_io.o

# target to build an object file
src/csp_io.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_io.c.o
.PHONY : src/csp_io.c.o

src/csp_io.i: src/csp_io.c.i
.PHONY : src/csp_io.i

# target to preprocess a source file
src/csp_io.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_io.c.i
.PHONY : src/csp_io.c.i

src/csp_io.s: src/csp_io.c.s
.PHONY : src/csp_io.s

# target to generate assembly for a file
src/csp_io.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_io.c.s
.PHONY : src/csp_io.c.s

src/csp_port.o: src/csp_port.c.o
.PHONY : src/csp_port.o

# target to build an object file
src/csp_port.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_port.c.o
.PHONY : src/csp_port.c.o

src/csp_port.i: src/csp_port.c.i
.PHONY : src/csp_port.i

# target to preprocess a source file
src/csp_port.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_port.c.i
.PHONY : src/csp_port.c.i

src/csp_port.s: src/csp_port.c.s
.PHONY : src/csp_port.s

# target to generate assembly for a file
src/csp_port.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_port.c.s
.PHONY : src/csp_port.c.s

src/csp_promisc.o: src/csp_promisc.c.o
.PHONY : src/csp_promisc.o

# target to build an object file
src/csp_promisc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_promisc.c.o
.PHONY : src/csp_promisc.c.o

src/csp_promisc.i: src/csp_promisc.c.i
.PHONY : src/csp_promisc.i

# target to preprocess a source file
src/csp_promisc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_promisc.c.i
.PHONY : src/csp_promisc.c.i

src/csp_promisc.s: src/csp_promisc.c.s
.PHONY : src/csp_promisc.s

# target to generate assembly for a file
src/csp_promisc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_promisc.c.s
.PHONY : src/csp_promisc.c.s

src/csp_qfifo.o: src/csp_qfifo.c.o
.PHONY : src/csp_qfifo.o

# target to build an object file
src/csp_qfifo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_qfifo.c.o
.PHONY : src/csp_qfifo.c.o

src/csp_qfifo.i: src/csp_qfifo.c.i
.PHONY : src/csp_qfifo.i

# target to preprocess a source file
src/csp_qfifo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_qfifo.c.i
.PHONY : src/csp_qfifo.c.i

src/csp_qfifo.s: src/csp_qfifo.c.s
.PHONY : src/csp_qfifo.s

# target to generate assembly for a file
src/csp_qfifo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_qfifo.c.s
.PHONY : src/csp_qfifo.c.s

src/csp_rdp.o: src/csp_rdp.c.o
.PHONY : src/csp_rdp.o

# target to build an object file
src/csp_rdp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_rdp.c.o
.PHONY : src/csp_rdp.c.o

src/csp_rdp.i: src/csp_rdp.c.i
.PHONY : src/csp_rdp.i

# target to preprocess a source file
src/csp_rdp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_rdp.c.i
.PHONY : src/csp_rdp.c.i

src/csp_rdp.s: src/csp_rdp.c.s
.PHONY : src/csp_rdp.s

# target to generate assembly for a file
src/csp_rdp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_rdp.c.s
.PHONY : src/csp_rdp.c.s

src/csp_rdp_queue.o: src/csp_rdp_queue.c.o
.PHONY : src/csp_rdp_queue.o

# target to build an object file
src/csp_rdp_queue.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_rdp_queue.c.o
.PHONY : src/csp_rdp_queue.c.o

src/csp_rdp_queue.i: src/csp_rdp_queue.c.i
.PHONY : src/csp_rdp_queue.i

# target to preprocess a source file
src/csp_rdp_queue.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_rdp_queue.c.i
.PHONY : src/csp_rdp_queue.c.i

src/csp_rdp_queue.s: src/csp_rdp_queue.c.s
.PHONY : src/csp_rdp_queue.s

# target to generate assembly for a file
src/csp_rdp_queue.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_rdp_queue.c.s
.PHONY : src/csp_rdp_queue.c.s

src/csp_route.o: src/csp_route.c.o
.PHONY : src/csp_route.o

# target to build an object file
src/csp_route.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_route.c.o
.PHONY : src/csp_route.c.o

src/csp_route.i: src/csp_route.c.i
.PHONY : src/csp_route.i

# target to preprocess a source file
src/csp_route.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_route.c.i
.PHONY : src/csp_route.c.i

src/csp_route.s: src/csp_route.c.s
.PHONY : src/csp_route.s

# target to generate assembly for a file
src/csp_route.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_route.c.s
.PHONY : src/csp_route.c.s

src/csp_rtable_cidr.o: src/csp_rtable_cidr.c.o
.PHONY : src/csp_rtable_cidr.o

# target to build an object file
src/csp_rtable_cidr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_rtable_cidr.c.o
.PHONY : src/csp_rtable_cidr.c.o

src/csp_rtable_cidr.i: src/csp_rtable_cidr.c.i
.PHONY : src/csp_rtable_cidr.i

# target to preprocess a source file
src/csp_rtable_cidr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_rtable_cidr.c.i
.PHONY : src/csp_rtable_cidr.c.i

src/csp_rtable_cidr.s: src/csp_rtable_cidr.c.s
.PHONY : src/csp_rtable_cidr.s

# target to generate assembly for a file
src/csp_rtable_cidr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_rtable_cidr.c.s
.PHONY : src/csp_rtable_cidr.c.s

src/csp_rtable_stdio.o: src/csp_rtable_stdio.c.o
.PHONY : src/csp_rtable_stdio.o

# target to build an object file
src/csp_rtable_stdio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_rtable_stdio.c.o
.PHONY : src/csp_rtable_stdio.c.o

src/csp_rtable_stdio.i: src/csp_rtable_stdio.c.i
.PHONY : src/csp_rtable_stdio.i

# target to preprocess a source file
src/csp_rtable_stdio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_rtable_stdio.c.i
.PHONY : src/csp_rtable_stdio.c.i

src/csp_rtable_stdio.s: src/csp_rtable_stdio.c.s
.PHONY : src/csp_rtable_stdio.s

# target to generate assembly for a file
src/csp_rtable_stdio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_rtable_stdio.c.s
.PHONY : src/csp_rtable_stdio.c.s

src/csp_service_handler.o: src/csp_service_handler.c.o
.PHONY : src/csp_service_handler.o

# target to build an object file
src/csp_service_handler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_service_handler.c.o
.PHONY : src/csp_service_handler.c.o

src/csp_service_handler.i: src/csp_service_handler.c.i
.PHONY : src/csp_service_handler.i

# target to preprocess a source file
src/csp_service_handler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_service_handler.c.i
.PHONY : src/csp_service_handler.c.i

src/csp_service_handler.s: src/csp_service_handler.c.s
.PHONY : src/csp_service_handler.s

# target to generate assembly for a file
src/csp_service_handler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_service_handler.c.s
.PHONY : src/csp_service_handler.c.s

src/csp_services.o: src/csp_services.c.o
.PHONY : src/csp_services.o

# target to build an object file
src/csp_services.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_services.c.o
.PHONY : src/csp_services.c.o

src/csp_services.i: src/csp_services.c.i
.PHONY : src/csp_services.i

# target to preprocess a source file
src/csp_services.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_services.c.i
.PHONY : src/csp_services.c.i

src/csp_services.s: src/csp_services.c.s
.PHONY : src/csp_services.s

# target to generate assembly for a file
src/csp_services.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_services.c.s
.PHONY : src/csp_services.c.s

src/csp_sfp.o: src/csp_sfp.c.o
.PHONY : src/csp_sfp.o

# target to build an object file
src/csp_sfp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_sfp.c.o
.PHONY : src/csp_sfp.c.o

src/csp_sfp.i: src/csp_sfp.c.i
.PHONY : src/csp_sfp.i

# target to preprocess a source file
src/csp_sfp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_sfp.c.i
.PHONY : src/csp_sfp.c.i

src/csp_sfp.s: src/csp_sfp.c.s
.PHONY : src/csp_sfp.s

# target to generate assembly for a file
src/csp_sfp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/csp_sfp.c.s
.PHONY : src/csp_sfp.c.s

src/drivers/usart/usart_kiss.o: src/drivers/usart/usart_kiss.c.o
.PHONY : src/drivers/usart/usart_kiss.o

# target to build an object file
src/drivers/usart/usart_kiss.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/drivers/usart/usart_kiss.c.o
.PHONY : src/drivers/usart/usart_kiss.c.o

src/drivers/usart/usart_kiss.i: src/drivers/usart/usart_kiss.c.i
.PHONY : src/drivers/usart/usart_kiss.i

# target to preprocess a source file
src/drivers/usart/usart_kiss.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/drivers/usart/usart_kiss.c.i
.PHONY : src/drivers/usart/usart_kiss.c.i

src/drivers/usart/usart_kiss.s: src/drivers/usart/usart_kiss.c.s
.PHONY : src/drivers/usart/usart_kiss.s

# target to generate assembly for a file
src/drivers/usart/usart_kiss.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/drivers/usart/usart_kiss.c.s
.PHONY : src/drivers/usart/usart_kiss.c.s

src/drivers/usart/usart_linux.o: src/drivers/usart/usart_linux.c.o
.PHONY : src/drivers/usart/usart_linux.o

# target to build an object file
src/drivers/usart/usart_linux.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/drivers/usart/usart_linux.c.o
.PHONY : src/drivers/usart/usart_linux.c.o

src/drivers/usart/usart_linux.i: src/drivers/usart/usart_linux.c.i
.PHONY : src/drivers/usart/usart_linux.i

# target to preprocess a source file
src/drivers/usart/usart_linux.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/drivers/usart/usart_linux.c.i
.PHONY : src/drivers/usart/usart_linux.c.i

src/drivers/usart/usart_linux.s: src/drivers/usart/usart_linux.c.s
.PHONY : src/drivers/usart/usart_linux.s

# target to generate assembly for a file
src/drivers/usart/usart_linux.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/drivers/usart/usart_linux.c.s
.PHONY : src/drivers/usart/usart_linux.c.s

src/interfaces/csp_if_can.o: src/interfaces/csp_if_can.c.o
.PHONY : src/interfaces/csp_if_can.o

# target to build an object file
src/interfaces/csp_if_can.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/interfaces/csp_if_can.c.o
.PHONY : src/interfaces/csp_if_can.c.o

src/interfaces/csp_if_can.i: src/interfaces/csp_if_can.c.i
.PHONY : src/interfaces/csp_if_can.i

# target to preprocess a source file
src/interfaces/csp_if_can.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/interfaces/csp_if_can.c.i
.PHONY : src/interfaces/csp_if_can.c.i

src/interfaces/csp_if_can.s: src/interfaces/csp_if_can.c.s
.PHONY : src/interfaces/csp_if_can.s

# target to generate assembly for a file
src/interfaces/csp_if_can.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/interfaces/csp_if_can.c.s
.PHONY : src/interfaces/csp_if_can.c.s

src/interfaces/csp_if_can_pbuf.o: src/interfaces/csp_if_can_pbuf.c.o
.PHONY : src/interfaces/csp_if_can_pbuf.o

# target to build an object file
src/interfaces/csp_if_can_pbuf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/interfaces/csp_if_can_pbuf.c.o
.PHONY : src/interfaces/csp_if_can_pbuf.c.o

src/interfaces/csp_if_can_pbuf.i: src/interfaces/csp_if_can_pbuf.c.i
.PHONY : src/interfaces/csp_if_can_pbuf.i

# target to preprocess a source file
src/interfaces/csp_if_can_pbuf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/interfaces/csp_if_can_pbuf.c.i
.PHONY : src/interfaces/csp_if_can_pbuf.c.i

src/interfaces/csp_if_can_pbuf.s: src/interfaces/csp_if_can_pbuf.c.s
.PHONY : src/interfaces/csp_if_can_pbuf.s

# target to generate assembly for a file
src/interfaces/csp_if_can_pbuf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/interfaces/csp_if_can_pbuf.c.s
.PHONY : src/interfaces/csp_if_can_pbuf.c.s

src/interfaces/csp_if_i2c.o: src/interfaces/csp_if_i2c.c.o
.PHONY : src/interfaces/csp_if_i2c.o

# target to build an object file
src/interfaces/csp_if_i2c.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/interfaces/csp_if_i2c.c.o
.PHONY : src/interfaces/csp_if_i2c.c.o

src/interfaces/csp_if_i2c.i: src/interfaces/csp_if_i2c.c.i
.PHONY : src/interfaces/csp_if_i2c.i

# target to preprocess a source file
src/interfaces/csp_if_i2c.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/interfaces/csp_if_i2c.c.i
.PHONY : src/interfaces/csp_if_i2c.c.i

src/interfaces/csp_if_i2c.s: src/interfaces/csp_if_i2c.c.s
.PHONY : src/interfaces/csp_if_i2c.s

# target to generate assembly for a file
src/interfaces/csp_if_i2c.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/interfaces/csp_if_i2c.c.s
.PHONY : src/interfaces/csp_if_i2c.c.s

src/interfaces/csp_if_kiss.o: src/interfaces/csp_if_kiss.c.o
.PHONY : src/interfaces/csp_if_kiss.o

# target to build an object file
src/interfaces/csp_if_kiss.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/interfaces/csp_if_kiss.c.o
.PHONY : src/interfaces/csp_if_kiss.c.o

src/interfaces/csp_if_kiss.i: src/interfaces/csp_if_kiss.c.i
.PHONY : src/interfaces/csp_if_kiss.i

# target to preprocess a source file
src/interfaces/csp_if_kiss.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/interfaces/csp_if_kiss.c.i
.PHONY : src/interfaces/csp_if_kiss.c.i

src/interfaces/csp_if_kiss.s: src/interfaces/csp_if_kiss.c.s
.PHONY : src/interfaces/csp_if_kiss.s

# target to generate assembly for a file
src/interfaces/csp_if_kiss.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/interfaces/csp_if_kiss.c.s
.PHONY : src/interfaces/csp_if_kiss.c.s

src/interfaces/csp_if_lo.o: src/interfaces/csp_if_lo.c.o
.PHONY : src/interfaces/csp_if_lo.o

# target to build an object file
src/interfaces/csp_if_lo.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/interfaces/csp_if_lo.c.o
.PHONY : src/interfaces/csp_if_lo.c.o

src/interfaces/csp_if_lo.i: src/interfaces/csp_if_lo.c.i
.PHONY : src/interfaces/csp_if_lo.i

# target to preprocess a source file
src/interfaces/csp_if_lo.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/interfaces/csp_if_lo.c.i
.PHONY : src/interfaces/csp_if_lo.c.i

src/interfaces/csp_if_lo.s: src/interfaces/csp_if_lo.c.s
.PHONY : src/interfaces/csp_if_lo.s

# target to generate assembly for a file
src/interfaces/csp_if_lo.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/interfaces/csp_if_lo.c.s
.PHONY : src/interfaces/csp_if_lo.c.s

src/interfaces/csp_if_tun.o: src/interfaces/csp_if_tun.c.o
.PHONY : src/interfaces/csp_if_tun.o

# target to build an object file
src/interfaces/csp_if_tun.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/interfaces/csp_if_tun.c.o
.PHONY : src/interfaces/csp_if_tun.c.o

src/interfaces/csp_if_tun.i: src/interfaces/csp_if_tun.c.i
.PHONY : src/interfaces/csp_if_tun.i

# target to preprocess a source file
src/interfaces/csp_if_tun.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/interfaces/csp_if_tun.c.i
.PHONY : src/interfaces/csp_if_tun.c.i

src/interfaces/csp_if_tun.s: src/interfaces/csp_if_tun.c.s
.PHONY : src/interfaces/csp_if_tun.s

# target to generate assembly for a file
src/interfaces/csp_if_tun.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/interfaces/csp_if_tun.c.s
.PHONY : src/interfaces/csp_if_tun.c.s

src/interfaces/csp_if_udp.o: src/interfaces/csp_if_udp.c.o
.PHONY : src/interfaces/csp_if_udp.o

# target to build an object file
src/interfaces/csp_if_udp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/interfaces/csp_if_udp.c.o
.PHONY : src/interfaces/csp_if_udp.c.o

src/interfaces/csp_if_udp.i: src/interfaces/csp_if_udp.c.i
.PHONY : src/interfaces/csp_if_udp.i

# target to preprocess a source file
src/interfaces/csp_if_udp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/interfaces/csp_if_udp.c.i
.PHONY : src/interfaces/csp_if_udp.c.i

src/interfaces/csp_if_udp.s: src/interfaces/csp_if_udp.c.s
.PHONY : src/interfaces/csp_if_udp.s

# target to generate assembly for a file
src/interfaces/csp_if_udp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libcsp.dir/build.make CMakeFiles/libcsp.dir/src/interfaces/csp_if_udp.c.s
.PHONY : src/interfaces/csp_if_udp.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... csp_arch"
	@echo "... csp_server_client"
	@echo "... if_zmq"
	@echo "... libcsp"
	@echo "... zmqproxy"
	@echo "... src/arch/posix/csp_clock.o"
	@echo "... src/arch/posix/csp_clock.i"
	@echo "... src/arch/posix/csp_clock.s"
	@echo "... src/arch/posix/csp_queue.o"
	@echo "... src/arch/posix/csp_queue.i"
	@echo "... src/arch/posix/csp_queue.s"
	@echo "... src/arch/posix/csp_semaphore.o"
	@echo "... src/arch/posix/csp_semaphore.i"
	@echo "... src/arch/posix/csp_semaphore.s"
	@echo "... src/arch/posix/csp_system.o"
	@echo "... src/arch/posix/csp_system.i"
	@echo "... src/arch/posix/csp_system.s"
	@echo "... src/arch/posix/csp_time.o"
	@echo "... src/arch/posix/csp_time.i"
	@echo "... src/arch/posix/csp_time.s"
	@echo "... src/arch/posix/pthread_queue.o"
	@echo "... src/arch/posix/pthread_queue.i"
	@echo "... src/arch/posix/pthread_queue.s"
	@echo "... src/crypto/csp_hmac.o"
	@echo "... src/crypto/csp_hmac.i"
	@echo "... src/crypto/csp_hmac.s"
	@echo "... src/crypto/csp_sha1.o"
	@echo "... src/crypto/csp_sha1.i"
	@echo "... src/crypto/csp_sha1.s"
	@echo "... src/csp_bridge.o"
	@echo "... src/csp_bridge.i"
	@echo "... src/csp_bridge.s"
	@echo "... src/csp_buffer.o"
	@echo "... src/csp_buffer.i"
	@echo "... src/csp_buffer.s"
	@echo "... src/csp_conn.o"
	@echo "... src/csp_conn.i"
	@echo "... src/csp_conn.s"
	@echo "... src/csp_crc32.o"
	@echo "... src/csp_crc32.i"
	@echo "... src/csp_crc32.s"
	@echo "... src/csp_debug.o"
	@echo "... src/csp_debug.i"
	@echo "... src/csp_debug.s"
	@echo "... src/csp_dedup.o"
	@echo "... src/csp_dedup.i"
	@echo "... src/csp_dedup.s"
	@echo "... src/csp_hex_dump.o"
	@echo "... src/csp_hex_dump.i"
	@echo "... src/csp_hex_dump.s"
	@echo "... src/csp_id.o"
	@echo "... src/csp_id.i"
	@echo "... src/csp_id.s"
	@echo "... src/csp_iflist.o"
	@echo "... src/csp_iflist.i"
	@echo "... src/csp_iflist.s"
	@echo "... src/csp_init.o"
	@echo "... src/csp_init.i"
	@echo "... src/csp_init.s"
	@echo "... src/csp_io.o"
	@echo "... src/csp_io.i"
	@echo "... src/csp_io.s"
	@echo "... src/csp_port.o"
	@echo "... src/csp_port.i"
	@echo "... src/csp_port.s"
	@echo "... src/csp_promisc.o"
	@echo "... src/csp_promisc.i"
	@echo "... src/csp_promisc.s"
	@echo "... src/csp_qfifo.o"
	@echo "... src/csp_qfifo.i"
	@echo "... src/csp_qfifo.s"
	@echo "... src/csp_rdp.o"
	@echo "... src/csp_rdp.i"
	@echo "... src/csp_rdp.s"
	@echo "... src/csp_rdp_queue.o"
	@echo "... src/csp_rdp_queue.i"
	@echo "... src/csp_rdp_queue.s"
	@echo "... src/csp_route.o"
	@echo "... src/csp_route.i"
	@echo "... src/csp_route.s"
	@echo "... src/csp_rtable_cidr.o"
	@echo "... src/csp_rtable_cidr.i"
	@echo "... src/csp_rtable_cidr.s"
	@echo "... src/csp_rtable_stdio.o"
	@echo "... src/csp_rtable_stdio.i"
	@echo "... src/csp_rtable_stdio.s"
	@echo "... src/csp_service_handler.o"
	@echo "... src/csp_service_handler.i"
	@echo "... src/csp_service_handler.s"
	@echo "... src/csp_services.o"
	@echo "... src/csp_services.i"
	@echo "... src/csp_services.s"
	@echo "... src/csp_sfp.o"
	@echo "... src/csp_sfp.i"
	@echo "... src/csp_sfp.s"
	@echo "... src/drivers/usart/usart_kiss.o"
	@echo "... src/drivers/usart/usart_kiss.i"
	@echo "... src/drivers/usart/usart_kiss.s"
	@echo "... src/drivers/usart/usart_linux.o"
	@echo "... src/drivers/usart/usart_linux.i"
	@echo "... src/drivers/usart/usart_linux.s"
	@echo "... src/interfaces/csp_if_can.o"
	@echo "... src/interfaces/csp_if_can.i"
	@echo "... src/interfaces/csp_if_can.s"
	@echo "... src/interfaces/csp_if_can_pbuf.o"
	@echo "... src/interfaces/csp_if_can_pbuf.i"
	@echo "... src/interfaces/csp_if_can_pbuf.s"
	@echo "... src/interfaces/csp_if_i2c.o"
	@echo "... src/interfaces/csp_if_i2c.i"
	@echo "... src/interfaces/csp_if_i2c.s"
	@echo "... src/interfaces/csp_if_kiss.o"
	@echo "... src/interfaces/csp_if_kiss.i"
	@echo "... src/interfaces/csp_if_kiss.s"
	@echo "... src/interfaces/csp_if_lo.o"
	@echo "... src/interfaces/csp_if_lo.i"
	@echo "... src/interfaces/csp_if_lo.s"
	@echo "... src/interfaces/csp_if_tun.o"
	@echo "... src/interfaces/csp_if_tun.i"
	@echo "... src/interfaces/csp_if_tun.s"
	@echo "... src/interfaces/csp_if_udp.o"
	@echo "... src/interfaces/csp_if_udp.i"
	@echo "... src/interfaces/csp_if_udp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

